#!/bin/bash
docker-compose up --build -d
echo -e ''
echo -e 'EXPLOITATION'
echo -e ''
echo -e 'Visit http://localhost:9070 to access the vulnerable web applications'
echo -e 'Use http://attackerserver:8888 to access the attacker hosting server from the vulnerable web app.'
echo -e 'Use http://http://169.254.169.254 to access the AWS metadata simulator from the vulnerable web app.'
echo -e ''
echo -e 'DEBUGGING'
echo -e ''
echo -e '+---------------------------------+----------------------------------------------------------------+'
echo -e '| docker containers               | How to access                                                  |'
echo -e '+---------------------------------+----------------------------------------------------------------+'
echo -e '| php vulnerable server           | docker container exec -it php-vulnserver-xxe bash              |'
echo -e '+---------------------------------+----------------------------------------------------------------+'
echo -e '| python vulnerable server        | docker container exec -it python-vulnserver-xxe bash           |'
echo -e '+---------------------------------+----------------------------------------------------------------+'
echo -e '| java vulnerable server          | docker container exec -it java-vulnserver-xxe bash             |'
echo -e '+---------------------------------+----------------------------------------------------------------+'
echo -e '| attacker server (file hosting ) | docker container exec -it attackerserver bash                  |'
echo -e '+---------------------------------+----------------------------------------------------------------+'
echo -e '| aws metadata simulator          | docker container exec -it aws-metadata-simulator bash          |'
echo -e '+---------------------------------+----------------------------------------------------------------+'